parameters:
  - name: pool_name
    displayName: agent pool location
    type: string
    default: default

resources:
 repositories:
   - repository: templates
     name: 'proy_ing/pipeline_templates'
     type: git
     ref: refs/heads/feature/devops


trigger:
  branches:
    include:
     - 13.0
  paths:
    include:
      - /*

pool:
  name: 'default'


extends:
  template: templates/azure-pipeline-odooapp.yml@templates
  parameters:
    sonarqube_project_key: '$(sonarqube_project_key)'
    sonarqube_project_name: 'product_barcode_generator_odoo'
    serviceConnection: sonarqube-connection
    sonarUrl: $(sonarqube_url)
    filter_version: "^13.0.[0-9\\.]+$"
    pool_name: ${{parameters.pool_name}}
    strategy_matrix:
      - name: main
        value: '.'
